Strs ← {"one"
        "two"
        "three"
        "four"
        "five"
        "six"
        "seven"
        "eight"
        "nine"}

Nums ← ↯ 9_1 "123456789"

Find ← /+×+1⇡9⊠(⊐⌕)

Solve ← /+≡(+⊢⇌:×10⊢.♭⍉⊠(⊐⊡)⊝⊚:□.) + Find Nums : Find Strs .

Solve ⬚@ ["two1nine"
          "eightwothree"
          "abcone2threexyz"
          "xtwone3four"
          "4nineeightseven2"
          "zoneight234"
          "7pqrstsixteen"]
